name: build
on: [push, pull_request]

jobs:
  NodeJS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
      - run: npm run compile
      - run: npm run test-node
  Browser:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
      - run: npm run compile
      - run: npm run bundle
      - run: npm run test-browser